//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 03:18:17 上午 CST 
//


package com.baobaotao.ws.server.springws.schema.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.baobaotao.ws.server.springws.schema.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndDate_QNAME = new QName("http://www.baobaotao.com/ws/server/springws/schema/messages/v2", "endDate");
    private final static QName _StartDate_QNAME = new QName("http://www.baobaotao.com/ws/server/springws/schema/messages/v2", "startDate");
    private final static QName _TopicType_QNAME = new QName("http://www.baobaotao.com/ws/server/springws/schema/messages/v2", "topicType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.baobaotao.ws.server.springws.schema.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRefinedTopicCountRequest }
     * 
     */
    public GetRefinedTopicCountRequest createGetRefinedTopicCountRequest() {
        return new GetRefinedTopicCountRequest();
    }

    /**
     * Create an instance of {@link GetRefinedTopicCountResponse }
     * 
     */
    public GetRefinedTopicCountResponse createGetRefinedTopicCountResponse() {
        return new GetRefinedTopicCountResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.baobaotao.com/ws/server/springws/schema/messages/v2", name = "endDate")
    public JAXBElement<XMLGregorianCalendar> createEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.baobaotao.com/ws/server/springws/schema/messages/v2", name = "startDate")
    public JAXBElement<XMLGregorianCalendar> createStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_StartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.baobaotao.com/ws/server/springws/schema/messages/v2", name = "topicType")
    public JAXBElement<String> createTopicType(String value) {
        return new JAXBElement<String>(_TopicType_QNAME, String.class, null, value);
    }

}
