//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 03:18:17 上午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.baobaotao.com/ws/server/springws/schema/messages/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.baobaotao.ws.server.springws.schema.v2;
